cmd_drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.o := aarch64-linux-gnu-gcc -Wp,-MD,drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/.rlm_protection.o.d -nostdinc -isystem /usr/lib/gcc-cross/aarch64-linux-gnu/4.8/include -I./arch/arm64/include -Iarch/arm64/include/generated/uapi -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -I./drivers/misc/mediatek/include -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Wno-format-security -std=gnu89 -mgeneral-regs-only -fno-pic -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1400 -fno-stack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -I./drivers/misc/mediatek/hibcore -I./drivers/misc/mediatek/include -I./drivers/misc/mediatek/include/mt-plat/mt8167/include -I./drivers/misc/mediatek/include/mt-plat -I./drivers/mmc/host/mediatek/mt8167 -D MTK_WCN_REMOVE_KERNEL_MODULE -D CONFIG_MTK_WCN_ARM64 -D WMT_IDC_SUPPORT=0 -D MTK_WCN_WMT_STP_EXP_SYMBOL_ABSTRACT -D MTK_WCN_BUILT_IN_DRIVER -UMT6620 -UMT6628 -UMT5931 -DCFG_SUPPORT_DEBUG_FS=0 -DWLAN_INCLUDE_PROC -DCFG_SUPPORT_AGPS_ASSIST=1 -DCFG_SUPPORT_TSF_USING_BOOTTIME=1 -DARP_MONITER_ENABLE=1 -DLINUX -DMT6630 -DCFG_SUPPORT_CHNL_CONFLICT_REVISE=0 -DCFG_SUPPORT_AEE=1 -DBUILD_QA_DBG=1 -DCFG_SUPPORT_PASSPOINT=0 -DCFG_HS20_DEBUG=0 -DCFG_ENABLE_GTK_FRAME_FILTER=0 -DCFG_MET_PACKET_TRACE_SUPPORT=1 -D_HIF_SDIO=1 -DDBG=0 -Idrivers/misc/mediatek/connectivity/wlan/gen3/os -Idrivers/misc/mediatek/connectivity/wlan/gen3/os/linux/include -Idrivers/misc/mediatek/connectivity/wlan/gen3/os/linux/hif/sdio/include -Idrivers/misc/mediatek/connectivity/wlan/gen3/include -Idrivers/misc/mediatek/connectivity/wlan/gen3/include/nic -Idrivers/misc/mediatek/connectivity/wlan/gen3/include/mgmt -I./drivers/misc/mediatek/base/power/include -DFW_CFG_SUPPORT    -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(rlm_protection)"  -D"KBUILD_MODNAME=KBUILD_STR(wlan_gen3)" -c -o drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.o drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.c

source_drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.o := drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.c

deps_drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.o := \

drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.o: $(deps_drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.o)

$(deps_drivers/misc/mediatek/connectivity/wlan/gen3/mgmt/rlm_protection.o):
